### ISSUE TITLE
Build failed due to missing tslFiles.bundle

### ISSUE THREAD

**Issue by oliverkuldmae** [open-eid/MOPP-iOS#134]
Attempting to build the source code after following the **Building source code with Xcode** section results in the following build error:  `error: .../MOPP-iOS/MoppApp/MoppApp/tslFiles.bundle: No such file or directory (in target 'shareExtension' from project 'MoppApp')`.

**Comment by martenrebane** [comment]
Issue fixed. You can download the latest source code on master. Installation instructions are updated and available in Wiki: [Building source code with Xcode](https://github.com/open-eid/MOPP-iOS/wiki/Building-source-code-with-Xcode)
