### ISSUE TITLE
Build Failed!

### ISSUE THREAD

**Issue by zahirquliyev** [open-eid/MOPP-iOS#146]
Hi,
Do followed all steps as written in documentation. Unfortunately getting error during build process. Below is output, please assist.

Initializing default MOPP configuration setup script: 
Brew is already installed
Swift-sh is already installed
error: The operation couldn’t be completed. (Script.ImportSpecification.DependencyName.E.0)

**Comment by kristelmerilain** [comment]
Apologies for the late response.
Please let us know if this issue still exists.
