### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by ChungDuc238** [open-eid/MOPP-iOS#365]
I'm still crashing my app with the MOPP-iOS.  App crash when I authenticate card ACR1255.
this is my code:
`func bluetoothReader(_ bluetoothReader: ABTBluetoothReader!, didAttach peripheral: CBPeripheral!, error: Error!) {`
         `if error != nil {`
`return`
` let cardData = CardReaderData(bytes: key)`
` reader.authenticate(withMasterKey: cardData .converToData() as Data)`
`}`

I got an error this line:  `reader.authenticate(withMasterKey: cardData .converToData() as Data)`
With the following errors in the output window:
`023-04-13 19:38:49.737994+0700 Runner[8459:2989758] -[ABTAcr1255uj1Reader checksumFromBuffer:length:]: unrecognized selector sent to instance 0x1051048d0`
`2023-04-13 19:38:49.738679+0700 Runner[8459:2989758] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ABTAcr1255uj1Reader checksumFromBuffer:length:]: unrecognized selector sent to instance 0x1051048d0'`
*** First throw call stack:
`(0x197f6b708 0x1aca757a8 0x197e6ebfc 0x197f6e260 0x197f70560 0x1008bd3c8 0x1008bba58 0x1008babdc 0x1008b0d78 0x1008b0e1c 0x1008bcc84 0x1b17efc44 0x1b17efdb0 0x1b17ec36c 0x1b17e1150 0x1b1808f78 0x1b17fc874 0x1033a80b4 0x1033a9de0 0x1033b1ef0 0x1033b2d48 0x1033b9ef0 0x197ee5340 0x197edf218 0x197ede308 0x1af561734 0x19a95c75c 0x19a961fcc 0x1008902a0 0x197b9acf8)`
`libc++abi: terminating with uncaught exception of type NSException`
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ABTAcr1255uj1Reader checksumFromBuffer:length:]: unrecognized selector sent to instance 0x1051048d0'
terminating with uncaught exception of type NSException
```
Can you help me fix this error?

**Comment by kristelmerilain** [comment]
We can see that you are using ACS software and Bluetooth card reader (ACR1255), which are not used or supported in RIA DigiDoc application.
List of supported card readers can be found here: https://github.com/open-eid/MOPP-iOS/wiki/Working-with-card-readers#supported-card-reader
We recommend you to contact ACS Support to figure out why it is not working: https://www.acs.com.hk/en/acs-worldwide/
